budget/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from accounts import views
from wallet import views  as wallet_views
from book import views as book_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", TemplateView.as_view(template_name='base.html'), name="home"),
    path("add_wallet/", wallet_views.WalletCreateView.as_view(), name="add_wallet"),
    path("list_wallet/", wallet_views.WalletListView.as_view(), name="list_wallet"),
    path("wallet/<int:pk>/", wallet_views.WalletDetailView.as_view(), name="detail_wallet"),
    path("cashflow/<int:pk>/", wallet_views.CashFlowUpdateView.as_view(), name="update_cashflow"),
    path("delete_wallet/<int:pk>/", wallet_views.DeleteWalletView.as_view(), name="delete_wallet"),
    path("add_cashflow/", wallet_views.CashFlowCreateView.as_view(), name="add_cashflow"),
    path('add_author/', book_views.CreateAuthorView.as_view(), name="add_author"),
    path('add_book/', book_views.CreateBookView.as_view(), name="create_book"),
    path('update_author/<int:pk>/', book_views.UpdateAuthorView.as_view(), name=""),
    path('delete_author/<int:pk>/', book_views.DeleteAuthorView.as_view(), name='delete_autor'),
    path("create_user/", views.CreateUserView.as_view(), name="create_user"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

wallet/models.py
from django.contrib.auth.models import User
from django.db import models

TYPES = (
    (1, 'income'),
    (2, 'expanse')
)


# Create your models here.

class Wallet(models.Model):
    name = models.CharField(max_length=50)
    balance = models.FloatField(default=0)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} stan: {self.balance}"


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class CashFlow(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    amount = models.FloatField(default=0)#100  -> 150
    category = models.ManyToManyField(Category, blank=True)
    date = models.DateField()
    type = models.IntegerField(choices=TYPES,  blank=False)


    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.pk is None:
            old_amount=0
        else:
            old_cf = CashFlow.objects.get(pk=self.pk)
            old_amount = old_cf.amount
        super().save(force_insert, force_update, using, update_fields)
        if self.type == 1:
            self.wallet.balance += self.amount - old_amount
        elif self.type == 2:
            self.wallet.balance -= self.amount - old_amount


        self.wallet.save()

wallet/forms.py
from django import forms
from django.core.exceptions import ValidationError

from wallet.models import CashFlow, Wallet


# def check_len(value):
#     if len(value) < 3:
#         raise ValidationError('Nazwa jest za krótka')
#
# def check_upper(value):
#     if not value[0].isupper():
#         raise ValidationError('Musi zaczynać sie wielką literą')
class WalletCreateForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Nazwa'}),
        # validators=[check_len, check_upper]
    )


class CashFlowCreateForm(forms.ModelForm):

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['wallet'].queryset = Wallet.objects.filter(owner=user)

    class Meta:
        model = CashFlow
        fields = "__all__"
        widgets = {
            'category': forms.CheckboxSelectMultiple,
            'date': forms.DateInput(attrs={'type': 'date'})
        }

class CashFlowCreateWalletForm(forms.ModelForm):

    class Meta:
        model = CashFlow
        exclude = ['wallet']
        widgets = {
            'category': forms.CheckboxSelectMultiple,
            'date': forms.DateInput(attrs={'type': 'date'}),
            'type':forms.RadioSelect()
        }

class CashFlowUpdateForm(forms.ModelForm):
    class Meta:
        model = CashFlow
        exclude = ['wallet', 'date', 'type']
        widgets = {
            'category': forms.CheckboxSelectMultiple
        }

wallet/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View

from wallet.forms import WalletCreateForm, CashFlowCreateForm, CashFlowUpdateForm, CashFlowCreateWalletForm
from wallet.models import Wallet, CashFlow


# Create your views here.
class WalletCreateView(LoginRequiredMixin, View):

    def get(self, request):

        form = WalletCreateForm()
        return render(request, 'form.html', {'form': form})

    def post(self, request):
        user = request.user
        form = WalletCreateForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            Wallet.objects.create(owner=user, name=name)
            return redirect('home')
        return render(request, 'form.html', {'form': form})

class WalletListView(LoginRequiredMixin, View):

    def get(self, request):
        wallets = Wallet.objects.filter(owner=request.user)
        return render(request, 'list.html', {'wallets': wallets})


class DeleteWalletView(UserPassesTestMixin, View):

    def test_func(self):
        user = self.request.user
        wallet = Wallet.objects.get(pk=self.kwargs['pk'])
        return wallet.owner == user


    def get(self, request, pk):
        wallet = Wallet.objects.get(pk=pk)
        return render(request, 'delete.html', {'wallet': wallet})

    def post(self, request, pk):
        operacja = request.POST.get('delete')
        if operacja == 'tak':
            wallet = Wallet.objects.get(pk=pk)
            wallet.delete()
        return redirect('list_wallet')


class CashFlowCreateView(LoginRequiredMixin, View):

    def get(self, request):
        form = CashFlowCreateForm(user=request.user)
        return render(request, 'form.html', {'form':form})


    def post(self, request):
        form = CashFlowCreateForm(request.POST, user=request.user)
        if form.is_valid():
            cf = form.save()
            return redirect('home')
        return render(request, 'form.html', {'form': form})


class WalletDetailView(UserPassesTestMixin, View):

    def test_func(self):
        user = self.request.user
        wallet = Wallet.objects.get(pk=self.kwargs['pk'])
        return wallet.owner == user

    def get(self, request, pk):
        wallet = Wallet.objects.get(pk=pk)
        form = CashFlowCreateWalletForm()
        return render(request, 'wallet.html', {'wallet': wallet, 'form':form})

    def post(self, request, pk):
        wallet = Wallet.objects.get(pk=pk)
        form = CashFlowCreateWalletForm(request.POST)
        if form.is_valid():
            cf = form.save(commit=False)
            cf.wallet = wallet
            cf.save()
            form.save_m2m()
            return redirect('detail_wallet', wallet.id)
        return render(request, 'wallet.html', {'wallet': wallet, 'form': form})


class CashFlowUpdateView(LoginRequiredMixin, View):

    def test_func(self):
        user = self.request.user
        cf = CashFlow.objects.get(pk=self.kwargs['pk'])
        return cf.wallet.owner == user

    def get(self, request, pk):
        cf = CashFlow.objects.get(pk=pk)
        form = CashFlowUpdateForm(instance=cf)
        return render(request, 'form.html', {'form': form})

    def post(self, request, pk):
        cf = CashFlow.objects.get(pk=pk)
        form = CashFlowUpdateForm(request.POST, instance=cf)
        if form.is_valid():
            form.save()
            return redirect('detail_wallet', cf.wallet.pk)
        return render(request, 'form.html', {'form': form})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'base.css' %}" rel="stylesheet">
</head>
<body class="conteiner">
{% if user.is_authenticated %}
    Witaj {{ user.username }}
{% endif %}
<div class="header">
    <ul class="nav">
        <li class="nav"><a href="{% url 'add_wallet' %}">Dodaj Portfel</a></li>
        <li class="nav"><a href="{% url 'list_wallet' %}">Portfele</a></li>
        <li class="nav"><a href="{% url 'add_cashflow' %}">Cashflow add</a></li>
        <li class="nav"><a href="#">ddd</a></li>
    </ul>
    <ul class="nav">
        {% if user.is_authenticated %}
            <li class="nav"><a href="{% url 'logout' %}">wyloguj</a> </li>
        {% else %}
            <li class="nav"><a href="{% url 'login' %}">zaloguj</a> </li>
        {% endif %}
    </ul>
</div>
<div class="cont">{% block content %}{% endblock %}</div>
<div class="footer">{{ data }} ala ma kota a kot nie ma ali <img src="{% static 'ja.jpeg' %}" width="50"> </div>
</body>
</html>w

templates/create_user.html
{% extends 'base.html' %}
{% block content %}
    <div style="margin: 5px">
        <div>
            {{ error }}
        </div>
        <form method="post">
            {% csrf_token %}
            <p>
                <input type="text" name="username" placeholder="login">
            </p>
            <p>
                <input type="password" name="password" placeholder="hasło">
            </p>
            <p>
                <input type="password" name="password2" placeholder="re-hasło">
            </p>
            <p>
                <input type="submit">
            </p>
        </form>
    </div>
{% endblock %}

templates/delete.html
{% extends 'base.html' %}
{% block content %}
    <p>
        czy jesteś pewien że chcesz usunąć {{ wallet }}
    </p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="tak" name="delete">
        <input type="submit" value="nie" name="delete">
    </form>
{% endblock %}

templates/delete_author.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
    {% csrf_token%}
     <input type="submit" value="Tak" name="action">
     <input type="submit" value="Nie" name="action">
    </form>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
    <ul>
        {% for author in authors %}
            <li>{{ author }} <a href="{% url 'delete_autor' author.id %}">X</a> </li>
        {% endfor %}
    </ul>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% block content %}
    <ul>
    {% for item in wallets %}
        <li><a href="{% url 'detail_wallet' item.pk %}"> {{ item }}</a> <a href="{% url 'delete_wallet' item.pk %}"><button>x</button></a> </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        <input type="text" name="username">
        <input type="password" name="password">
        <input type="submit">
    </form>
{% endblock %}

templates/wallet.html
{% extends 'base.html' %}
{% block content %}
    <div>
        {{ wallet.name }} : {{ wallet.balance }}
    </div>
    <div>
        <table>
            <thead>
            <tr>
                <th>Kwota</th>
                <th>Typ</th>
                <th>data</th>
                <th>Kategorie</th>
            </tr>
            </thead>
            <tbody>
            {% for cf in wallet.cashflow_set.all %}
                <tr>
                    <td><a href="{% url 'update_cashflow' cf.pk %}"> {{ cf.amount }}</a></td>
                    <td>{{ cf.get_type_display }}</td>
                    <td>{{ cf.date }}</td>
                    <td>
                        <ul>
                            {% for category in cf.category.all %}
                                <li>{{ category }}</li>
                            {% endfor %}
                        </ul>

                    </td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
    </div>
{% endblock %}